---
apiVersion: v1 
kind: Pod
metadata:
  name: catalogue
  labels:
    name: catalogue
    tier: app
spec:
  containers:
    - name: catalogue
      image: avpreddy/catalogue:v1
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  selector:
    name: catalogue
    tier: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080